Repository SebaUbuntu/android_packages_apps_Selfie, pull requests merged in 2022-08, with the labels that each got.

#35 Selfie: Add camera flip animation
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/res/animator/rotate_180.xml
  app/src/main/res/drawable/ic_flip_camera.xml
  app/src/main/res/drawable/ic_flip_camera_anim.xml
  app/src/main/res/layout/activity_main.xml
Labels: ui

#34 Selfie: Add label for zoom level
  app/build.gradle
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: ui

#37 Selfie: Fix crash on no zoom capabilities
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
Labels: bug

#32 Selfie: Implement QR scanner
  app/build.gradle
  app/src/main/java/org/lineageos/selfie/ImageProxyExt.kt
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/java/org/lineageos/selfie/QrImageAnalyzer.kt
  app/src/main/java/org/lineageos/selfie/SharedPreferencesExt.kt
  app/src/main/java/org/lineageos/selfie/utils/CameraMode.kt
  app/src/main/res/drawable/ic_qr.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: features

#38 Selfie: Rebind optimizations
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
Labels: enhancement

#40 Selfie: Add 4x4 grid mode
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/java/org/lineageos/selfie/SharedPreferencesExt.kt
  app/src/main/java/org/lineageos/selfie/ui/GridView.kt
  app/src/main/java/org/lineageos/selfie/utils/GridMode.kt
  app/src/main/res/drawable/ic_grid_on.xml
  app/src/main/res/drawable/ic_grid_on_3.xml
  app/src/main/res/drawable/ic_grid_on_4.xml
  app/src/main/res/layout/activity_main.xml
Labels: ui, features

#45 Selfie: Default to CAPTURE_MODE_MINIMIZE_LATENCY
  app/src/main/java/org/lineageos/selfie/SharedPreferencesExt.kt
  app/src/main/res/xml/root_preferences.xml
Labels: enhancement

#51 Selfie: Make zoom slider linear
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: ui

#29 Selfie: Implement shutter sound
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/java/org/lineageos/selfie/SettingsActivity.kt
  app/src/main/java/org/lineageos/selfie/SharedPreferencesExt.kt
  app/src/main/java/org/lineageos/selfie/utils/CameraSoundsUtils.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/root_preferences.xml
Labels: features

#56 Selfie: Force DEFAULT_BACK_CAMERA for barcode scanner
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
Labels: bug, ui

#55 Selfie: Make QrImageAnalyzer use BottomSheetDialog
  app/src/main/java/org/lineageos/selfie/QrImageAnalyzer.kt
  app/src/main/res/drawable/ic_copy.xml
  app/src/main/res/drawable/ic_drag_handle.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/layout/qr_bottom_sheet_dialog.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: ui

#57 Luca textclass
  app/src/main/java/org/lineageos/selfie/QrImageAnalyzer.kt
Labels: enhancement

#63 Selfie: Implement "Bright screen"
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/java/org/lineageos/selfie/SharedPreferencesExt.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/root_preferences.xml
Labels: features

#71 Selfie: Implement volume key shutter feature
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
Labels: features

#68 Selfie: Fix crash after double tapping shutter button in video mode
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
Labels: bug

#72 Selfie: Don't reserve space for icons in Settings
  app/src/main/res/xml/root_preferences.xml
Labels: ui

#73 Selfie: Import switch style from SettingsLib
  app/src/main/res/color/settingslib_switch_thumb_color.xml
  app/src/main/res/color/settingslib_switch_track_color.xml
  app/src/main/res/drawable/settingslib_switch_thumb.xml
  app/src/main/res/drawable/settingslib_switch_track.xml
  app/src/main/res/values/themes.xml
Labels: ui

#76 Selfie: Handle volume key long press for video mode
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
Labels: features

#58 Selfie: Pass inverted YUV to MultiFormatReader as well
  app/src/main/java/org/lineageos/selfie/QrImageAnalyzer.kt
Labels: enhancement

#85 Selfie: Use maven repository for our CameraX builds
  app/build.gradle
  app/libs/camera-camera2-release.aar
  app/libs/camera-core-release.aar
  app/libs/camera-extensions-release.aar
  app/libs/camera-lifecycle-release.aar
  app/libs/camera-mlkit-vision-release.aar
  app/libs/camera-video-release.aar
  app/libs/camera-view-release.aar
  settings.gradle
Labels: enhancement

#82 Selfie: Rebuild camerax with changes that let us reuse recorder
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  settings.gradle
Labels: bug, enhancement

#88 Selfie: Add KEYCODE_FOCUS/KEYCODE_CAMERA support
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
Labels: features

#90 Selfie: Enable minify/shrink/proguard
  app/build.gradle
Labels: enhancement

#94 Selfie: Import count down view from Camera2
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/java/org/lineageos/selfie/ui/CountDownView.kt
  app/src/main/res/layout/activity_main.xml
Labels: ui

#96 Selfie: Add support for video recording pause/resume
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/res/drawable/avd_video_recording_pause.xml
  app/src/main/res/drawable/avd_video_recording_resume.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: features

#97 Selfie: Introduce CameraState enum
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/java/org/lineageos/selfie/utils/CameraState.kt
Labels: enhancement

#98 Selfie: Make video recording timer cancellable
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/java/org/lineageos/selfie/ui/CountDownView.kt
Labels: features
