Repository SebaUbuntu/android_packages_apps_Selfie, pull requests merged in 2022-09, with the labels that each got.

#100 Selfie: Add monochrome icon support
  app/src/main/res/drawable/ic_launcher_monochrome.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
Labels: enhancement

#103 Selfie: Add shortcuts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/res/drawable/ic_shortcut_qr.xml
  app/src/main/res/drawable/ic_shortcut_selfie.xml
  app/src/main/res/drawable/ic_shortcut_video.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/shortcuts.xml
Labels: enhancement, features

#105 Selfie: Add white background for shortcut icons
  app/src/main/res/drawable/ic_shortcut_qr.xml
  app/src/main/res/drawable/ic_shortcut_selfie.xml
  app/src/main/res/drawable/ic_shortcut_video.xml
Labels: bug

#106 Selfie: Convert gradle scripts to kotlin
  app/build.gradle
  app/build.gradle.kts
  build.gradle
  build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#108 Selfie: Relocate app shortcuts out of resources
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/lineageos/selfie/MainActivity.kt
  app/src/main/java/org/lineageos/selfie/utils/ShortcutsUtils.kt
  app/src/main/res/xml/shortcuts.xml
Labels: enhancement

#109 Selfie: Add .dev to gradle package name
  app/build.gradle.kts
Labels: enhancement
